### ISSUE TITLE
Interface versimpelen voor jan met de pet

### ISSUE THREAD

**Issue by jasper-smit** [rijksuniversiteit-groningen/b2-ExamAnalysis#20]

**Comment by allardnaber** [comment]
Voorstel:
![image](https://user-images.githubusercontent.com/11871362/71174500-a2683100-2265-11ea-8dc8-24b95882fb32.png)

dus:
- profielen: label veranderen in "Use Settings", in de knop alleen de naam, niet de tekst "Use defaults"
- Formula: "Linear" weg
- Custom Expression hiernoemen naar Custom Formula
- Het veld + uitleg voor de Custom Formula pas tonen als Custom Formula is aangeklikt.
