### ISSUE TITLE
Afronden op halve cijfers

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-ExamAnalysis#23]
Verzoek Wim:
weet jij of het in Ttlyse en GEA mogelijk is om bij een cijferbepaling af te ronden op halve cijfers (e.g. 6,6 wordt een 6,5; 7,3 wordt een 7,5)? Ik sprak gisteren de onderwijsdirecteur van Psychologie en ik heb de indruk dat zij mogelijk heel veel extra tijd/moeite investeren in een service die wij gewoon al (kunnen) bieden - momenteel laten zij docenten bij MC-tentamens de cijfers handmatig afronden

1. In principe wordt afgerond naar halve cijfers. Een 7.24 is dus een 7, een 7.25 en hoger een 7.5, etc.
2. De enige uitzondering hierop zit hem inderdaad tussen de 5 en 6. Omdat de status van een 5.5 vaak onduidelijkheid oproept, ronden ze tussen de 5 en 6 af naar hele cijfers. Een 5.5 en hoger wordt dus een 6 (en is daarmee een voldoende). 5.49 en lager wordt een 5 (en is dus een onvoldoende).

**Comment by allardnaber** [comment]
Als extra optie bij "Rounding of grades"
![image](https://user-images.githubusercontent.com/11871362/81683158-029a8200-9456-11ea-9e6d-fbc52e96230b.png)

Dus de regel:
* is cijfer >= 5,25 & < 5,75 , rond af op 0 decimalen (zodat 5,25 tot 5,5 een 5 wordt en 5,5 tot 5,75 een 6 wordt). Als je liever > 5 en < 6 als grenzen gebruikt mag dat ook, iets verklarender. Zelfde effect.
* anders: x = cijfer :   (afronden(x * 2, 1 decimaal)) / 2

cijfer vervolgens weergeven met 1 cijfer achter de komma, dus 8,0 of 8,5 , etc.

Dan bij het cijferoverzicht het onderste kopje veranderen zodat hier gewoon dezelfde teksten staan als bij het maken van een analyse:
![image](https://user-images.githubusercontent.com/11871362/81684643-6ec9b580-9457-11ea-86bf-cb2899872ab4.png)

**Comment by magiclars-off** [comment]
Done
